[project]
name = "modbuddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4",
    "bs4",
    "patool",
    "PySide6",
    "PySide6-Addons",
    "PySide6-Essentials",
    "requests",
]


[dependency-groups]
dev = [
    "pyside6-stubs>=6.7.3.0",
    "pytest>=8.4.1",
    "pytest-cov>=4.0.0",
    "pytest-qt>=4.5.0",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-requests>=2.32.4.20250809",
    "pre-commit>=2.20.0",
    "tox-uv>=1.11.3",
    "deptry>=0.23.0",
    "mypy>=0.991",
    "ruff>=0.11.5",
    "mkdocs>=1.4.2",
    "mkdocs-material>=8.5.10",
    "mkdocstrings[python]>=0.26.1",
]


[tool.pylint.'MAIN']
extension-pkg-allow-list = ["PySide6"]

[tool.mypy]
strict = false
files = ["src"]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.pylint]
max-line-length = 120

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "YTT", # flake8-2020
    # "F",      # Pyflakes
    #"E",      # Error
    #"W",      # Warning
    #"C90",    # mccabe
    #"I",      # isort
    #"N",      # pep8-naming
    #"D",      # pydocstyle
    #"UP",  # pyupgrade
    #"ANN",    # flake8-annotations
    #"ASYNC",  # flake8-async
    "S",   # flake8-bandit
    "BLE", # flake8-blind-except
    "FBT", # flake8-boolean-trap
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    #"COM",    # flake8-commas
    "CPY", # flake8-copyright
    #"C4",     # flake8-comprehensions
    #"DTZ",    # flake8-datetimez
    "T10", # flake8-debugger
    "DJ",  # flake8-django
    #"EM",     # flake8-errmsg
    "EXE", # flake8-executable
    #"FA",  # flake8-future-annotations
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    #"LOG",    # flake8-logging
    #"G",      # flake8-logging-format
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PYI", # flake8-pyi
    #"PT",     # flake8-pytest-style
    #"Q",      # flake8-quotes
    #"RSE",    # flake8-raise
    #"RET",    # flake8-return
    #"SLF",    # flake8-self
    "SLOT", # flake8-slots
    #"SIM",    # flake8-simplify
    #"TID",    # flake8-tidy-imports
    #"TC",     # flake8-type-checking
    #"INT",    # flake8-gettext
    #"ARG",    # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "TD",  # flake8-todos
    "FIX", # flake8-fixme
    "ERA", # eradicate
    # "PD",  # pandas-vet
    "PGH", # pygrep-hooks
    "PL",  # Pylint
    "C",   # Convention

    #"TRY",    # tryceratops
    "FLY",  # flynt
    "NPY",  # NumPy-specific rules
    "FAST", # FastAPI
    "AIR",  # Airflow
    #"PERF",   # Perflint
    "FURB", # refurb
    #"DOC",    # pydoclint
    #"RUF",    # Ruff-specific rules


    # Recommend to ignore due to formatter:
    "W191",   # tab-indentation
    "E111",   # indentation-with-invalid-multiple
    "E114",   # indentation-with-invalid-multiple-comment
    "E117",   # over-indented
    "D206",   # indent-with-spaces
    "D300",   # triple-single-quotes
    "Q000",   # bad-quotes-inline-string
    "Q001",   # bad-quotes-multiline-string
    "Q002",   # bad-quotes-docstring
    "Q003",   # avoidable-escaped-quote
    "COM812", # missing-trailing-comma
    "COM819", # prohibited-trailing-comma
    "ISC001", # single-line-implicit-string-concatenation
    "ISC002", # multi-line-implicit-string-concatenation
    # Recommended to ignore:
    "C901",   # complexity check
    "D100",   # ignore missing docs
    "D101",   # missing docstring in public class
    "D102",   # missing docstring in public method
    "D103",   # missing docstring in public function
    "D104",   # missing docstring in public package
    "D105",   # missing docstring in magic method
    "D106",   # missing docstring in public nested class
    "D107",   # missing docstring in __init__
    "D200",   # one-line docstring should fit on one line
    "D203",   # one blank line before class docstring
    "D204",   # one blank line after class docstring
    "D205",   # blank line after docstring
    "D211",   # no blank lines allowed before class docstring
    "D212",   # multi-line docstring summary should start at first line
    "D400",   # first line should end with period
    "D401",   # first line should be in imperative mood
    "D406",   # section name should end with newline
    "D407",   # missing dashed underline after section
    "D415",   # first line should end with period, question mark, or exclamation
    "E266",   # too many leading '#' for block comment
    "E402",   # false positives for local imports
    "E501",   # line too long
    "FIX002", # too verbose descriptions of todos
    "TD002",  # missing author in TODO
    "TD003",  # missing issue link in TODO
    "TRY003", # external messages in exceptions are too verbose
    "RUF001", # ruff-specific rule


    #white space
    # "w293",
    # "w291",
    "ANN401", # Disable typing.Any for annotations
    "N802",   # Function name should be lowercase
]

fixable = ["ALL"]
unfixable = ["F401"]


[tool.lint.pydocstyle]
convention = "google"

[tool.lint.pylint]
# Maximum number of arguments for function / method
max-args = 20
# Maximum number of boolean expressions in a if statement
max-bool-expr = 10
# Maximum number of branch for function / method body
max-branches = 100
# Maximum number of locals for function / method body
max-locals = 15
# Maximum number of nested blocks for function / method body
max-nested-blocks = 5
# Maximum number of positional arguments allowed for a function or method definition
max-positional-args = 10
# Maximum number of public methods for a class (see R0904).
max-public-methods = 30
# Maximum number of return statements allowed for a function or method body
max-returns = 10
# Maximum number of statements in function / method body
max-statements = 1000


[tool.lint.mccabe]
max-complexity = 10

[tool.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]
